# Generated by Django 5.2.1 on 2025-09-17 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("teacher", "Teacher"),
                            ("professor", "Professor"),
                            ("instructor", "Instructor"),
                            ("student", "Student"),
                            ("researcher", "Researcher"),
                            ("assistant", "Assistant"),
                            ("admin", "Admin"),
                            ("developer", "Developer"),
                            ("frontend_developer", "Frontend Developer"),
                            ("backend_developer", "Backend Developer"),
                            ("fullstack_developer", "Full Stack Developer"),
                            ("ui_ux_designer", "UI/UX Designer"),
                            ("content_creator", "Content Creator"),
                            ("curriculum_developer", "Curriculum Developer"),
                            ("educational_consultant", "Educational Consultant"),
                            ("academic_advisor", "Academic Advisor"),
                            ("librarian", "Librarian"),
                            ("school_administrator", "School Administrator"),
                            ("education_coordinator", "Education Coordinator"),
                            ("tutor", "Tutor"),
                            ("teaching_assistant", "Teaching Assistant"),
                            ("education_technologist", "Education Technologist"),
                            ("trainer", "Trainer"),
                            ("mentor", "Mentor"),
                            ("performance_tester", "Performance Tester"),
                            ("other", "Other"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AF", "Afghanistan"),
                            ("PS", "Palestine"),
                            ("EG", "Egypt"),
                            ("SD", "Sudan"),
                            ("NG", "Nigeria"),
                            ("US", "United States"),
                            ("CA", "Canada"),
                            ("BR", "Brazil"),
                            ("UK", "United Kingdom"),
                            ("DE", "Germany"),
                            ("IN", "India"),
                            ("CN", "China"),
                            ("JP", "Japan"),
                            ("KR", "South Korea"),
                            ("SA", "Saudi Arabia"),
                            ("AE", "United Arab Emirates"),
                            ("TR", "Turkey"),
                            ("PK", "Pakistan"),
                            ("ID", "Indonesia"),
                            ("MY", "Malaysia"),
                            ("SG", "Singapore"),
                            ("AU", "Australia"),
                            ("NZ", "New Zealand"),
                            ("ZA", "South Africa"),
                            ("KE", "Kenya"),
                            ("ET", "Ethiopia"),
                            ("MA", "Morocco"),
                            ("FR", "France"),
                            ("IT", "Italy"),
                            ("ES", "Spain"),
                            ("RU", "Russia"),
                            ("MX", "Mexico"),
                            ("AR", "Argentina"),
                            ("CO", "Colombia"),
                            ("VN", "Vietnam"),
                            ("TH", "Thailand"),
                            ("IR", "Iran"),
                            ("IQ", "Iraq"),
                            ("SY", "Syria"),
                            ("LB", "Lebanon"),
                            ("JO", "Jordan"),
                            ("OT", "Other"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("ar", "Arabic"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "secondary_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("ar", "Arabic"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics"),
                ),
                ("website_url", models.URLField(blank=True, null=True)),
                (
                    "friends",
                    models.ManyToManyField(
                        blank=True,
                        related_name="friend_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfilePrivacySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_visibility",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("friends_of_friends", "Friends of Friends"),
                            ("friends_only", "Friends Only"),
                            ("nobody", "Nobody"),
                        ],
                        default="everyone",
                        help_text="Who can find you in search results",
                        max_length=20,
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("friends_only", "Friends Only"),
                            ("private", "Private"),
                        ],
                        default="friends_only",
                        help_text="Who can view your full profile details",
                        max_length=20,
                    ),
                ),
                (
                    "show_full_name",
                    models.BooleanField(
                        default=True,
                        help_text="Show your first and last name in search results and profile",
                    ),
                ),
                (
                    "show_email",
                    models.BooleanField(
                        default=False,
                        help_text="Show your email address in your profile (not recommended)",
                    ),
                ),
                (
                    "allow_friend_requests",
                    models.BooleanField(
                        default=True,
                        help_text="Allow other users to send you friend requests",
                    ),
                ),
                (
                    "allow_chat_invites",
                    models.BooleanField(
                        default=True,
                        help_text="Allow other users to send you chat invitations",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_settings",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile Privacy Settings",
                "verbose_name_plural": "User Profile Privacy Settings",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FriendSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "suggested_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "suggested_user")},
            },
        ),
        migrations.CreateModel(
            name="ProfileFriendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message to include with the friend request.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the friend request was sent.",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_requests",
                        to="users.userprofile",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_requests",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Friend Request",
                "verbose_name_plural": "Profile Friend Requests",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sender", "receiver"),
                        name="unique_pending_friend_request",
                    )
                ],
            },
        ),
    ]
