# Generated by Django 5.2.1 on 2025-05-21 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=1000, null=True)),
                ('occupation', models.CharField(blank=True, choices=[], max_length=64, null=True)),
                ('country', models.CharField(blank=True, choices=[], max_length=64, null=True)),
                ('preferred_language', models.CharField(blank=True, choices=[], max_length=64, null=True)),
                ('secondary_language', models.CharField(blank=True, choices=[], max_length=64, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('friends', models.ManyToManyField(blank=True, related_name='friend_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
