# Generated by Django 5.2.1 on 2025-05-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('CA', 'Canada'), ('UK', 'United Kingdom'), ('DE', 'Germany'), ('IN', 'India'), ('OT', 'Other')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('student', 'Student'), ('assistant', 'Assistant'), ('admin', 'Admin'), ('frontend_developer', 'Frontend Developer'), ('backend_developer', 'Backend Developer'), ('other', 'Other')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='secondary_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic')], max_length=64, null=True),
        ),
    ]
