# Generated by Django 5.2.1 on 2025-05-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('PL', 'Palestine'), ('EG', 'Egypt'), ('SD', 'Sudan'), ('NG', 'Nigeria'), ('US', 'United States'), ('CA', 'Canada'), ('BR', 'Brazil'), ('UK', 'United Kingdom'), ('DE', 'Germany'), ('IN', 'India'), ('CN', 'China'), ('JP', 'Japan'), ('KR', 'South Korea'), ('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates'), ('TR', 'Turkey'), ('PK', 'Pakistan'), ('ID', 'Indonesia'), ('MY', 'Malaysia'), ('SG', 'Singapore'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('ZA', 'South Africa'), ('KE', 'Kenya'), ('ET', 'Ethiopia'), ('MA', 'Morocco'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('RU', 'Russia'), ('MX', 'Mexico'), ('AR', 'Argentina'), ('CO', 'Colombia'), ('VN', 'Vietnam'), ('TH', 'Thailand'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('SY', 'Syria'), ('LB', 'Lebanon'), ('JO', 'Jordan'), ('OT', 'Other')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('professor', 'Professor'), ('instructor', 'Instructor'), ('student', 'Student'), ('researcher', 'Researcher'), ('assistant', 'Assistant'), ('admin', 'Admin'), ('frontend_developer', 'Frontend Developer'), ('backend_developer', 'Backend Developer'), ('fullstack_developer', 'Full Stack Developer'), ('ui_ux_designer', 'UI/UX Designer'), ('content_creator', 'Content Creator'), ('curriculum_developer', 'Curriculum Developer'), ('educational_consultant', 'Educational Consultant'), ('academic_advisor', 'Academic Advisor'), ('librarian', 'Librarian'), ('school_administrator', 'School Administrator'), ('education_coordinator', 'Education Coordinator'), ('tutor', 'Tutor'), ('teaching_assistant', 'Teaching Assistant'), ('education_technologist', 'Education Technologist'), ('trainer', 'Trainer'), ('mentor', 'Mentor'), ('other', 'Other')], max_length=64, null=True),
        ),
    ]
