# Generated by Django 5.2.1 on 2025-05-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_userprofile_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="website_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
