# Generated by Django 5.2.1 on 2025-06-17 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfilePrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('friends_of_friends', 'Friends of Friends'), ('friends_only', 'Friends Only'), ('nobody', 'Nobody')], default='everyone', help_text='Who can find you in search results', max_length=20)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('friends_only', 'Friends Only'), ('private', 'Private')], default='friends_only', help_text='Who can view your full profile details', max_length=20)),
                ('show_full_name', models.BooleanField(default=True, help_text='Show your first and last name in search results and profile')),
                ('show_email', models.BooleanField(default=False, help_text='Show your email address in your profile (not recommended)')),
                ('allow_friend_requests', models.BooleanField(default=True, help_text='Allow other users to send you friend requests')),
                ('allow_chat_invites', models.BooleanField(default=True, help_text='Allow other users to send you chat invitations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'User Profile Privacy Settings',
                'verbose_name_plural': 'User Profile Privacy Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
