# Generated by Django 5.2.1 on 2025-06-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefriendrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message to include with the friend request.', max_length=500, null=True),
        ),
    ]
