# Generated by Django 5.2.1 on 2025-06-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profilefriendrequest_message'),
        ('users', '0007_userprofileprivacysettings'),
    ]

    operations = [
    ]
