from .. import UsersAppTestCase

# TODO: implement full authentication flow test once email confirmation is in place
# class AuthenticationFlowTests(TestCase):
#     def test_signup_flow_for_non_existing_user(self):
#         with TestStep("1. User Starts Verification"):
#             ...
#         with TestStep("2. User tries to confirm with wrong code"):
#             ...
#         with TestStep("3. User tries to confirm with correct code."):
#             ...
#         with TestStep("4. User finishes signup, obtains access token"):
#             ...
#         with TestStep("5. Access token can be used to access API endpoints requiring auth"):
#             ...
#         with TestStep("6. User logs out"):
#             ...
#         with TestStep("7. The original access token no longer works"):
#             ...
        