# Generated by Django 5.2.1 on 2025-06-28 22:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_alter_chatroom_options_alter_message_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('outline', models.TextField(blank=True, max_length=1000, null=True)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic')], max_length=64, null=True)),
                ('country', models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('PL', 'Palestine'), ('EG', 'Egypt'), ('SD', 'Sudan'), ('NG', 'Nigeria'), ('US', 'United States'), ('CA', 'Canada'), ('BR', 'Brazil'), ('UK', 'United Kingdom'), ('DE', 'Germany'), ('IN', 'India'), ('CN', 'China'), ('JP', 'Japan'), ('KR', 'South Korea'), ('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates'), ('TR', 'Turkey'), ('PK', 'Pakistan'), ('ID', 'Indonesia'), ('MY', 'Malaysia'), ('SG', 'Singapore'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('ZA', 'South Africa'), ('KE', 'Kenya'), ('ET', 'Ethiopia'), ('MA', 'Morocco'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('RU', 'Russia'), ('MX', 'Mexico'), ('AR', 'Argentina'), ('CO', 'Colombia'), ('VN', 'Vietnam'), ('TH', 'Thailand'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('SY', 'Syria'), ('LB', 'Lebanon'), ('JO', 'Jordan'), ('OT', 'Other')], max_length=64, null=True)),
                ('subject', models.CharField(blank=True, choices=[('math', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('cs', 'Computer Science'), ('it', 'Information Technology'), ('engineering', 'Engineering'), ('datasci', 'Data Science'), ('ai', 'Artificial Intelligence'), ('envsci', 'Environmental Science'), ('astronomy', 'Astronomy'), ('stats', 'Statistics'), ('robotics', 'Robotics'), ('electronics', 'Electronics'), ('psych', 'Psychology'), ('sociology', 'Sociology'), ('polisci', 'Political Science'), ('economics', 'Economics'), ('anthropology', 'Anthropology'), ('intlrel', 'International Relations'), ('criminology', 'Criminology'), ('history', 'History'), ('philosophy', 'Philosophy'), ('literature', 'Literature'), ('linguistics', 'Linguistics'), ('religion', 'Religious Studies'), ('cultural', 'Cultural Studies'), ('classics', 'Classics'), ('visualart', 'Visual Arts'), ('music', 'Music'), ('performing', 'Performing Arts'), ('architecture', 'Architecture'), ('design', 'Graphic Design'), ('film', 'Film & Media Studies'), ('photo', 'Photography'), ('fashion', 'Fashion Design'), ('business', 'Business Administration'), ('accounting', 'Accounting'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('hrm', 'Human Resource Management'), ('entrepreneurship', 'Entrepreneurship'), ('project', 'Project Management'), ('supplychain', 'Supply Chain Management'), ('education', 'Education'), ('earlyedu', 'Early Childhood Education'), ('specialedu', 'Special Education'), ('english', 'English Language'), ('foreignlang', 'Foreign Languages'), ('translation', 'Translation Studies'), ('tesol', 'TESOL / ESL'), ('law', 'Law'), ('legal', 'Legal Studies'), ('constitutional', 'Constitutional Law'), ('publicpolicy', 'Public Policy'), ('politicaltheory', 'Political Theory'), ('medicine', 'Medicine'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('publichealth', 'Public Health'), ('nutrition', 'Nutrition'), ('veterinary', 'Veterinary Science'), ('dentistry', 'Dentistry'), ('biomed', 'Biomedical Science'), ('physicaltherapy', 'Physical Therapy')], max_length=64, null=True)),
                ('visiblity', models.CharField(choices=[('Public', 'public'), ('Restricted', 'restricted'), ('Private', 'private')], default='private', max_length=64)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, default=datetime.datetime(2099, 12, 31, 23, 59, 59), null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('allow_join_requests', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='chat.chatroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_chatrooms', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Teacher', 'teacher'), ('Student', 'student'), ('Assistant', 'assistant')], default='student', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('enrolled', 'Enrolled'), ('invited', 'Invited')], default='pending', max_length=64)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(help_text='The type of the content object', on_delete=django.db.models.deletion.CASCADE, related_name='course_contents', to='contenttypes.contenttype')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='courses.course')),
            ],
        ),
    ]
