# Generated by Django 5.2.1 on 2025-08-21 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_options_alter_message_options_and_more'),
        ('courses', '0002_coursemembership_unique_user_course_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='visiblity',
            new_name='visibility',
        ),
        migrations.AlterField(
            model_name='course',
            name='outline',
            field=models.TextField(blank=True, help_text='A brief description of the course.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='What your Course is called..', max_length=128),
        ),
        migrations.AlterField(
            model_name='coursechatroom',
            name='chatroom',
            field=models.ForeignKey(help_text='The chatroom that is associated with the course.', on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='chat.chatroom'),
        ),
        migrations.AlterField(
            model_name='coursechatroom',
            name='course',
            field=models.ForeignKey(help_text='The course that the chatroom is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='course_chatrooms', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='coursechatroom',
            name='created_by',
            field=models.ForeignKey(help_text='The user who created the chatroom.', on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursemembership',
            name='course',
            field=models.ForeignKey(help_text='The course that the user is a member of.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='coursemembership',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('assistant', 'Assistant')], default='student', help_text='The role of the user in the course. (student, assistant, teacher)', max_length=32),
        ),
        migrations.AlterField(
            model_name='coursemembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('enrolled', 'Enrolled'), ('invited', 'Invited')], default='enrolled', help_text='The status of the user in the course. (pending, enrolled, invited)', max_length=64),
        ),
        migrations.AlterField(
            model_name='coursemembership',
            name='user',
            field=models.ForeignKey(help_text='The user who is a member of the course.', on_delete=django.db.models.deletion.CASCADE, related_name='course_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="The order of the module within the course's list of modules."),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='title',
            field=models.CharField(blank=True, help_text='What your Module is called.', max_length=128, null=True),
        ),
    ]
