# Generated by Django 5.2.1 on 2025-08-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_outline_alter_course_title_and_more'),
        ('courses', '0003_rename_visiblity_course_visibility_and_more'),
    ]

    operations = [
    ]
