
# Generated by Django 5.2.1 on 2025-09-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_merge_20250825_0624"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AF", "Afghanistan"),
                    ("PS", "Palestine"),
                    ("EG", "Egypt"),
                    ("SD", "Sudan"),
                    ("NG", "Nigeria"),
                    ("US", "United States"),
                    ("CA", "Canada"),
                    ("BR", "Brazil"),
                    ("UK", "United Kingdom"),
                    ("DE", "Germany"),
                    ("IN", "India"),
                    ("CN", "China"),
                    ("JP", "Japan"),
                    ("KR", "South Korea"),
                    ("SA", "Saudi Arabia"),
                    ("AE", "United Arab Emirates"),
                    ("TR", "Turkey"),
                    ("PK", "Pakistan"),
                    ("ID", "Indonesia"),
                    ("MY", "Malaysia"),
                    ("SG", "Singapore"),
                    ("AU", "Australia"),
                    ("NZ", "New Zealand"),
                    ("ZA", "South Africa"),
                    ("KE", "Kenya"),
                    ("ET", "Ethiopia"),
                    ("MA", "Morocco"),
                    ("FR", "France"),
                    ("IT", "Italy"),
                    ("ES", "Spain"),
                    ("RU", "Russia"),
                    ("MX", "Mexico"),
                    ("AR", "Argentina"),
                    ("CO", "Colombia"),
                    ("VN", "Vietnam"),
                    ("TH", "Thailand"),
                    ("IR", "Iran"),
                    ("IQ", "Iraq"),
                    ("SY", "Syria"),
                    ("LB", "Lebanon"),
                    ("JO", "Jordan"),
                    ("OT", "Other"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
